# Generated by Django 2.1.7 on 2019-03-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this book.', to='shelf.Genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
