# Generated by Django 2.1.7 on 2019-03-12 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_auto_20190312_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
    ]
