# Generated by Django 2.1.7 on 2019-03-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0003_auto_20190312_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
