# Generated by Django 2.1.7 on 2019-03-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0006_auto_20190312_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
