# Generated by Django 2.1.7 on 2019-03-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0010_auto_20190313_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
