# Generated by Django 2.1.7 on 2019-03-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0011_auto_20190317_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
